name: todo_list_application
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  intl: ^0.20.2
  kanban_board: 
    git: 
      url: https://github.com/KimKyungWon0519/FlutterKanbanBoard
      ref: main
  responsive_builder: ^0.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
